services:
  mongo:
    image: mongo:8.0.9
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: 'false'
